using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TopShelfService.Models
{
    public class Exam
    {
        public int Id { get; set; } 
        public string PatientId { get; set; }  // As Generated By Scanner
        public string PatientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public string ExamDate { get; set; }  // Formated as "MM/DD/YYYY:
        public string PatientBirthDate { get; set; } // Formated as "MM/DD/YYYY"
        public int NumOfExams { get; set; }
        public string ExamLocation { get; set; } // As Generated By Scanner
    }
}
